services:

  db:
    image: postgres:17.5-alpine
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - 5432:5432

  adminer:
    image: adminer:5.3.0
    ports:
      - 8080:8080
