services:
  api:
    build: .
    container_name: api
    environment:
      APP_ENV: ${APP_ENV}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      LOKI_URL: ${LOKI_URL}
      LOKI_USER: ${LOKI_USER}
      LOKI_PASSWORD: ${LOKI_PASSWORD}
    ports:
      - 4000:8000
    depends_on:
      - db

  db:
    image: postgres:17.5-alpine
    shm_size: 128mb
    container_name: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432

  adminer:
    image: adminer:5.3.0
    container_name: adminer
    ports:
      - 8080:8080
    depends_on:
      - db
